# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

#on: push
on:  fork

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt-hotspot'
        server-id: github 
        settings-path: ${{ github.workspace }} 

    - name: Build with Maven
      run: mvn -B package --file follow-coin-compute/pom.xml -Dmaven.test.skip=true
    - uses: actions/upload-artifact@v4
      with:
        path: /home/runner/work/follow-coin/follow-coin/follow-coin-compute/target/follow-coin-compute-0.0.1-SNAPSHOT.jar


  build-image:
        runs-on: ubuntu-latest
        needs: build

        steps:
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: eu-central-1
              
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v2
            
            # is needed for the dockerfile
          - name: check out code
            uses: actions/checkout@v3

          - name: download java artifact
            uses: actions/download-artifact@master
            with:
              path: follow-coin-compute-0.0.1-SNAPSHOT.jar
    
          - name: Build, tag, and push docker image to Amazon ECR
            env:
              REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              REPOSITORY: follow-coin/follow-coin-compute
              IMAGE_TAG: ${{ github.sha }}
            run: |
              docker build --file ./follow-coin-compute/Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
              docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG



            


